# Source
if [[ -f "$HOME/.antigen/antigen.zsh" ]]; then
    source "$HOME/.antigen/antigen.zsh"
    antigen use oh-my-zsh
    antigen bundle git
    antigen bundle heroku
    antigen bundle pip
    antigen bundle lein
    antigen bundle command-not-found
    antigen bundle systemd
    antigen bundle bundler
    antigen bundle tmux
    antigen bundle vi-mode
    antigen bundle cp
    antigen bundle colorize
    antigen bundle encode64
    antigen bundle zsh-users/zsh-completions
    antigen bundle zsh-users/zsh-history-substring-search
    antigen bundle zsh-users/zsh-docker
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle zsh-users/zsh-autosuggestions
    antigen theme steeef
    antigen apply
fi
source "$HOME/.zsh_aliases"

# History settings
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# Aliases for history with date format stamps
case $HIST_STAMPS in
  "mm/dd/yyyy") alias history='omz_history -f' ;;
  "dd.mm.yyyy") alias history='omz_history -E' ;;
  "yyyy-mm-dd") alias history='omz_history -i' ;;
  "") alias history='omz_history' ;;
  *) alias history="omz_history -t '$HIST_STAMPS'" ;;
esac

# Plugins and completions
plugins=(git docker terraform zsh-syntax-highlighting zsh-autosuggestions)
fpath+=("$HOME/.config/hcloud/completion/zsh")
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# Load additional configurations if available
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
# Check for keychain
if command -v keychain >/dev/null 2>&1; then
    eval $(keychain --ignore-missing --quiet --eval --agents ssh ~/.ssh/ssh-phife.key ~/.ssh/ssh-mg-precipoint.key)
else
    echo "keychain not installed, falling back to default ssh-agent"
fi

# Custom history management function
function omz_history {
  zparseopts -E c=clear l=list
  if [[ -n "$clear" ]]; then
    echo -n >| "$HISTFILE"
    echo >&2 History file deleted. Reload the session to see its effects.
  elif [[ -n "$list" ]]; then
    builtin fc "$@"
  else
    builtin fc "$@" -l 1
  fi
}
# Export environment variables (move these to .zshenv for better practice)
export ZSH="$HOME/.antigen/bundles/robbyrussell/oh-my-zsh"
export PATH=/usr/local/bin:$PATH
export HCLOUD_TOKEN=$(cat "$HOME/.hcloud_token") # Use a secure file for the token
export EDITOR=/usr/bin/vim
export BROWSER=/usr/bin/chromium

# Keybindings
# Fuzzy history search with Ctrl-R
#bindkey '^R' history-incremental-pattern-search-backward
